### PR TITLE
Unhardcode icon file type for GNU/Linux launcher

### PR DESCRIPTION
**Pull request by palob**
Since you install the icon to a location compliant with [freedesktop.org standards](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) (``usr/share/pixmaps``) you don't need to specify the icon file extension in the `.desktop` launcher. It will be found anyway.

This facilitates the use of non-PNG (e.g. SVG) app icon themes.
Cf. this [example `.desktop` launcher](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#example).

### CODE REVIEW

**Comment by jhasse** [comment]
flatpak-builder doesn't seem to like it: 

```
Error loading desktop file: Failed to find icon: Failed to find icon wxformbuilder
```
https://travis-ci.org/wxFormBuilder/wxFormBuilder/jobs/337753457

**Comment by palob** [comment]
Maybe the icon should rather be installed to ``usr/share/icons/hicolor/<size>/apps`` which is the no.1 standard location. I haven't delved into Flatpak yet myself, @bil-elmoussaoui any idea what's the issue here?

**Comment by bil-elmoussaoui** [comment]
@palob  I will take a look soon!

**Comment by bil-elmoussaoui** [comment]
The icon name used on the desktop file doesn't follow the RDNN conventions, so you should use rename-destkop, rename-icon and rename-appdata on the JSON file

**Pull request closed without merging**
