### PR TITLE
wxButton fixups

### PR DESCRIPTION
**Pull request by sodevel**
Fixes the issues reported here #427 and here #417

### CODE REVIEW

**Comment by sodevel** [comment]
Maybe resurrecting wxBU_AUTODRAW is not a good idea, after all the project file upgrade just removed it so everyone has to add it again. I checked the wxWidgets sources and it seems osx is the only affected port, gtk and msw just create a normal wxButton with wxBU_EXACTFIT and wxBU_NOTEXT in the wxBitmapButton constructor, only osx adds extra margins when that style is passed. It looks like osx actually can not produce a correct result without that style, so maybe we should do what wxWidgets does by default, always add that style in the generator templates.

Looks like a regression in wxWidgets to me, should be further analyzed.

**Comment by jhasse** [comment]
> after all the project file upgrade just removed it so everyone has to add it again.

We could still save people some trouble which haven't upgraded to 3.8.0 yet.

**Comment by sodevel** [comment]
Since this is deprecated and most probably a bug in wxWidgets i would prefer to do the same like they do. They use it as default and most users probably won't specify style flags at all because there is no need so this is in fact always specified, simply specifiy this flags always in the generator templates for now.

**Comment by jhasse** [comment]
Thanks for the PR.

**Pull request merged**
