### PR TITLE
Trivial changes to make build against wx3.1.1-rc pass

### PR DESCRIPTION
**Pull request by nohal**
At first glance the result seems pretty usable (And for example #348 seems not to be there anymore...)

### CODE REVIEW

**Comment by nohal** [comment]
Have to have a look - I am normally not using Homebrew wxmac at all as I need backward compatibility all the way to OS X 10.7 etc.

**Comment by nohal** [comment]
- `brew install wxmac --devel` - currently at 3.1.0 - Unusable as the property grid is broken. (This will likely get fixed as soon as 3.1.1 replaces it in a few days)
- `brew install wxmac --HEAD` - Same positive result as my local build, #348 seems gone.

FWIW, there is a behavioral change in the property grid - with older versions, hitting Enter in a property grid cell persisted the value and left the cell (And that for me was the usual cause of #348, although not the only one as the video there shows), this is not the case with wx 3.1.1 - hitting Enter in the property grid cell does nothing.

**Comment by jhasse** [comment]
And just `brew install wxmac`?

**Comment by nohal** [comment]
There #348 is present - this is how wxFB 3.6.2 was built (And I had the same result locally at the moment). This PR changes nothing on that (Although it does not break the build against wx 3.0 as we can see on Travis).

**Comment by jhasse** [comment]
Okay. I don't have a Mac so I can't test any of it ;)

But it sounds reasonable, thanks for the fix :)

**Pull request merged**
