### PR TITLE
Fix the wxFBBitmapProperty 'ico_size' values and wxFormBuilder crash when the 'Load From Icon Resource' 'resource_name' property is changed

### PR DESCRIPTION
**Pull request by tomay3000**
Use **Squash and merge** option to exclude the commits history.
[https://help.github.com/articles/about-pull-request-merges/](https://help.github.com/articles/about-pull-request-merges/)

### CODE REVIEW

**Comment by jhasse** [comment]
I have no idea what this is about, sorry. Please describe your change a little bit more.

**Comment by tomay3000** [comment]
@jhasse, Take a look at the files changed and ignore the 12 commits.
This is about the main wxPropertyGrid when using ribbon bars under windows, you have the option to load icons from resources.
So when you select '**Load From Icon Resource**' from the dropdown list of the **wxFBBitmapProperty** property category, then some weird values for '**ico_size**' property will be instead of the deafault ones: **(-1; -1)**. and if you try to change these values then wxFormBuilder will crash.

**Comment by jhasse** [comment]
"Files changed" only shows this for me:

```diff
-		if(childVals.Count() > 2)
-		{
-			Item(2)->SetValue( childVals[2]);
-		}
+		//if(childVals.Count() > 2)
+		//{
+		//	Item(2)->SetValue( childVals[2]);
+		//}
```

I don't understand how this fixes the bug you described?!?

**Comment by tomay3000** [comment]
it actually fixes the bug.
The changes I have made, just is commenting the code that trigers the bug.

Have you tried to reproduce it as I decribed (with and without the fix) ?

Thank you foryour understanding.

**Comment by tomay3000** [comment]
Take a look at this screenshot to understand what I'm talking about:
untitled

**Comment by jhasse** [comment]
While it does fix your bug (or workaround it), I'm not sure if it's okay to remove that. It might be used by other code in wxFormBuilder.

**Comment by tomay3000** [comment]
I spent more than three days trying to understand Most of wxFormBuilder's code (believe me it is a mess!) .
if only the GUI was written using wxFormBuilder itself (it could be easier).

That bug I am talking about, will make wxFormBuilder crash also if you try to edit these property values.
if only anybody else could reproduce it and then apply the patch to see the results, then it will confirmed.

**Comment by jhasse** [comment]
> believe me it is a mess!

I know ;)

> That bug I am talking about, will make wxFormBuilder crash also if you try to edit these property values.

I couldn't reproduce the crash, only the non-sense values. If I understand it correctly your patch simply doesn't update the ico_size property, which avoids the garbage values, but still doesn't sound like the final solution for me.

Also `wxFBBitmapProperty::UpdateChildValues` might be used by other parts which now won't work? I really don't know, unfortunately there are no automated tests for any of this :(

**Comment by ctfyui** [comment]
@tomay3000 It seems we have the same problem (#419).

**Comment by tomay3000** [comment]
@ctfyui I did fixed it in my wxFormBuilder version, take a look at the changed files.

**Comment by jhasse** [comment]
Closing in favor of #425

**Comment by tomay3000** [comment]
Thank you.

**Pull request closed without merging**
