### PR TITLE
Removed deprecated AddLabelTool

### PR DESCRIPTION
**Pull request by osnipezzini**

### CODE REVIEW

**Comment by sodevel** [comment]
I can merge the first commit but not the second one, i am not going to make a new release yet. Can you force push this PR without the second commit please so i don't have to cherry-pick from your repo? Also for the future please don't base a PR on your master branch, use a separate feature branch.

**Comment by osnipezzini** [comment]
But why you don't want to compile a new working release ?

Why work with a version compiled a more then one year ago ??

I' m go try to send PR without second commit , but please release a new version or make a compilation working tutorial , but i tryed instructions on README.md but not worked.

**Comment by sodevel** [comment]
A PR should focus on one task, fixing some code and making a release are two tasks.

A release involves more than just changing some version numbers (and apparently you missed some, the CI fails for a real reason this time) and can't be done alone by a PR. Because of some outstanding issues and time constraints on my side right now i don't want to take the extra steps to make a release.

At least for windows you can download the latest CI builds from the Actions tab of this site, otherwise you have to build from source yourself currently. The documentation about building should be current and working, there is one outstanding issue #575 that causes runtime failures on linux which can be fixed by moving the libraries to the correct location manually. Otherwise you can try to build with Premake instead.

If that doesn't help, open an issue and describe your build problem, i am sure it can be solved.

**Comment by sodevel** [comment]
Superseeded by #585

**Pull request closed without merging**
