### PR TITLE
improvements to the commit: 29692a6

### PR DESCRIPTION
**Pull request by tomay3000**

### CODE REVIEW

**Comment by jhasse** [comment]
Any idea why the macOS build fails?

**Comment by tomay3000** [comment]
actually, the linux build which failed. It it an automated build system from Travis.
and from the Travis log, it says:
`../../../src/maingui.cpp:50:27: fatal error: wx/xrc/xh_aui.h: No such file or directory
 #include <wx/xrc/xh_aui.h>
                           ^`
This is nonsense.
it succeded in both Windows and OSX.

**Comment by nohal** [comment]
`xh_aui.h` did not exist in WX 3.1.0 currently used by the flatpak, all that's needed should probably be to switch `org.wxformbuilder.wxFormBuilder.json` to use 3.1.1

**Comment by jhasse** [comment]
Wouldn't it be better to let the if check for > 3100?

**Comment by tomay3000** [comment]
I am currently downloading wxWidgets v3.1.0 to see what have been changed, because I am currently using version 3.1.1

**Comment by tomay3000** [comment]
It turns out that @nohal is right. `wx/xrc/xh_auinotbk.h` file has not changed from v**3.0.x** to v**3.1.0**.
The changes applied only in version **3.1.0** (I don't know about version **3.1.0-rc**).
I have made a direct github fixes from the editor.
Build is in process...

**Comment by jhasse** [comment]
Looks good 👍

**Comment by tomay3000** [comment]
Thank you ;)

**Pull request merged**
