### PR TITLE
force-wx-config option for automake is now optional, this is useful for custom wxWidgets builds.

### PR DESCRIPTION
**Pull request by tomay3000**
it is now possible to build wxFormBuilder without the force-wx-config option.

### CODE REVIEW

**Comment by tomay3000** [comment]
The second commit (**3aa96c9**) has been added automatically to the pull request, It was commited for my own repo only.
I have submitted only the first commit (**5c87359**) to this pull request.

**Comment by jhasse** [comment]
Do the following to remove the second commit:

```
git checkout 5c87359
git checkout -b force-wx-config
git push -u origin force-wx-config
```

And then create a PR from this branch :)

**Comment by tomay3000** [comment]
Done ;)

**Comment by jhasse** [comment]
#363

**Pull request closed without merging**
