### PR TITLE
fix Windows (MSYS2) build instruction

### PR DESCRIPTION
**Pull request by mengguang**
Tested on latest version msys2 and wxFormBuilder .

### CODE REVIEW

**Comment by sodevel** [comment]
Ok, i missed the closing quotes during the last update, but i had to remove the symlink to `bfd_stdint.h` because this file is not present in the current GitHub Virtual Environment anymore. I thought they updated MSYS2 and the file is not present in recent versions anymore?

**Comment by mengguang** [comment]
bfd_stdint.h exists at /mingw32/include/binutils/bfd_stdint.h, but the build script can not find it.   
so I need to link it to /mingw32/include/bfd_stdint.h, otherwise the build will fail.  
I tested on a fresh install of latest version of msys2 (msys2-x86_64-20210725.exe)  more than 2 times. 
the complete build fail message:  
```
$ make config=release
==== Building plugin-interface (release) ====
xrcconv.cpp
wizard.cpp
Linking plugin-interface
==== Building TiCPP (release) ====
Creating obj/Release/TiCPP
ticpp.cpp
tinystr.cpp
tinyxml.cpp
tinyxmlerror.cpp
tinyxmlparser.cpp
Linking TiCPP
==== Building additional-components-plugin (release) ====
Creating obj/Release/additional-components-plugin
additional.cpp
Linking additional-components-plugin
==== Building common-components-plugin (release) ====
Creating obj/Release/common-components-plugin
common.cpp
Linking common-components-plugin
==== Building containers-components-plugin (release) ====
Creating obj/Release/containers-components-plugin
containers.cpp
Linking containers-components-plugin
==== Building forms-components-plugin (release) ====
Creating obj/Release/forms-components-plugin
forms.cpp
Linking forms-components-plugin
==== Building layout-components-plugin (release) ====
Creating obj/Release/layout-components-plugin
layout.cpp
Linking layout-components-plugin
==== Building wxFormBuilder (release) ====
Creating obj/Release/wxFormBuilder
maingui.cpp
codegen.cpp
codeparser.cpp
codewriter.cpp
cppcg.cpp
luacg.cpp
phpcg.cpp
pythoncg.cpp
xrccg.cpp
stack.cpp
In file included from ../../../src/dbg_stack_trace/stack.cpp:22:
C:/msys64/mingw32/include/bfd.h:44:10: fatal error: bfd_stdint.h: No such file or directory
   44 | #include "bfd_stdint.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [wxFormBuilder.make:207: obj/Release/wxFormBuilder/stack.o] Error 1
make: *** [Makefile:45: wxFormBuilder] Error 2

```

**Comment by sodevel** [comment]
This is strange, according to the MSYS2 package registry the latest version of [binutils](https://packages.msys2.org/package/mingw-w64-i686-binutils?repo=mingw32) 2.37-2 does not contain `bfd_stdint.h` anymore. Are you sure you updated everything of MSYS2 and got the latest version (i don't use MSYS2 so i don't know how you can check this)?

**Comment by mengguang** [comment]
I tested one more time and finally found the reason:  
I need to execute `pacman -Syu` to get the latest version of packages.   
After that,  the bfd_stdint.h is not needed anymore.  
My bad.  
May be we can prepend `pacman -Syu`  in the instruction, so fewer people got confused.

**Comment by sodevel** [comment]
Yes, maybe you can update this PR to include that information.

**Comment by mengguang** [comment]
OK.  
I added a new commit to add pacman -Syu in the instructions and remove the bfd_stdint.h link.

**Comment by mengguang** [comment]
Tested on freshly installed msys2 environment.

**Pull request merged**
